version: "3.9"
name: tracklyrics
services:
  db:
    container_name: tracklyrics-db
    image: postgres:latest
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: track-lyrics
    ports:
      - "5432:5432"
    volumes:
      - ./tracklyrics-db:/var/lib/postgresql/data
    networks:
      - db

  db-hom:
    container_name: tracklyrics-db-hom
    image: postgres:latest
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: track-lyrics-hom
    ports:
      - "5434:5432"
    volumes:
      - ./tracklyrics-db-hom:/var/lib/postgresql/data

  cache:
    container_name: tracklyrics-redis
    image: redis:7.4-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - cache

networks:
  db:

  cache:
