import { Video } from "@/models/video";

export const videos: Video[] = [
  {
    title: "A Bar Song (Tipsy)",
    artist: "Shaboozey",
    uuid: "f8c6fcd4-31b6-4ac1-b15e-6d4e3c7f4dec",
    releaseYear: 2024,
    linkYoutube: "https://www.youtube.com/watch?v=t7bQwwqW-Hc",
    qtyViews: 0,
    language: "English",
    genre: "Country",
    username: "heitorvaldeger",
    thumbnail: "https://img.youtube.com/vi_webp/t7bQwwqW-Hc/maxresdefault.webp",
  },
  {
    title: "Titanium",
    artist: "David Guetta, Sia",
    uuid: "a6d7a424-490c-4081-965a-26d2d9abc331",
    releaseYear: 2011,
    linkYoutube: "https://www.youtube.com/watch?v=JRfuAukYTKg",
    qtyViews: 0,
    language: "English",
    genre: "Electronica",
    username: "heitorvaldeger",
    thumbnail: "https://img.youtube.com/vi_webp/90RLzVUuXe4/maxresdefault.webp",
  },
  {
    title: "A Bar Song (Tipsy)",
    artist: "Shaboozey",
    uuid: "f8c6fcd4-31b6-4ac1-b15e-6d4e3c7f4de2",
    releaseYear: 2024,
    linkYoutube: "https://www.youtube.com/watch?v=t7bQwwqW-Hc",
    qtyViews: 0,
    language: "English",
    genre: "Country",
    username: "heitorvaldeger",
    thumbnail: "https://img.youtube.com/vi_webp/t7bQwwqW-Hc/maxresdefault.webp",
  },
  {
    title: "A Bar Song (Tipsy)",
    artist: "Shaboozey",
    uuid: "f8c6fcd4-31b6-4ac1-b15e-6d4e3c7f4de5",
    releaseYear: 2024,
    linkYoutube: "https://www.youtube.com/watch?v=t7bQwwqW-Hc",
    qtyViews: 0,
    language: "English",
    genre: "Country",
    username: "heitorvaldeger",
    thumbnail: "https://img.youtube.com/vi_webp/t7bQwwqW-Hc/maxresdefault.webp",
  },
  {
    title: "Titanium",
    artist: "David Guetta, Sia",
    uuid: "a6d7a424-490c-4081-965a-26d2d9abc333",
    releaseYear: 2011,
    linkYoutube: "https://www.youtube.com/watch?v=JRfuAukYTKg",
    qtyViews: 0,
    language: "English",
    genre: "Electronica",
    username: "heitorvaldeger",
    thumbnail: "https://img.youtube.com/vi_webp/90RLzVUuXe4/maxresdefault.webp",
  },
];
